### ISSUE TITLE
Error Encountered

### ISSUE THREAD

**Issue by hematic** [EvotecIT/PSWinDocumentation#1]
Running this in verbose 

VERBOSE: Start-ActiveDirectoryDocumentation - Getting domain information
Get-GPO : The term 'Get-GPO' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\marshph-adm\Documents\WindowsPowerShell\Modules\pswindocumentation\0.0.5\Private\PSADDomain.ps1:26 char:35
+     $ADSnapshot.GroupPolicies = $(Get-GPO -Domain $Domain -All)
+                                   ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-GPO:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PrzemyslawKlys** [comment]
You need to install GPMC.

```
Install-WindowsFeature –Name GPMC
```

or 

```
Import-Module servermanager
Add-WindowsFeature –Name GPMC
```

GPMC = Group Policy Management Console, GPMC via PowerShell

Documentation: https://technet.microsoft.com/de-de/library/hh967461(v=wps.630).aspx

I guess I need to add prerequisites at some point.
