### ISSUE TITLE
Unable to find type [ListItemType]

### ISSUE THREAD

**Issue by carlosdoliveira** [EvotecIT/PSWinDocumentation#20]
It occurs when I try to run the script for Office 365 creating the following object

![image](https://user-images.githubusercontent.com/23587299/62649050-6d001e00-b92a-11e9-9bbd-f09f03e75e24.png)

``` PowerShell
Unable to find type [ListItemType].
At C:\Users\cdani\OneDrive\Área de Trabalho\report.ps1:58 char:35
+                 TocListItemType = [ListItemType]::Numbered
+                                   ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ListItemType:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```
In the following lines you can find the script I used: 
``` Powershell
Import-Module PSWinDocumentation
Import-Module PSWinDocumentation.O365
$Document = [ordered]@{
    Configuration     = [ordered] @{
        Prettify       = @{
            CompanyName        = 'Evotec'
            UseBuiltinTemplate = $true
            CustomTemplatePath = ''
            Language           = 'en-US'
        }
[...]
            SectionO365Introduction                 = [ordered] @{
                ### Enables section
                Use             = $true;
                ### Decides how TOC should be visible
                TocEnable       = $True
                TocText         = 'Scope'
                TocListLevel    = 0
                **TocListItemType = [ListItemType]::Numbered**
                TocHeadingType  = [HeadingType]::Heading1
                ### Text is added before table/list
                Text            = ""
                TextAlignment   = [Alignment]::Both
                PageBreaksAfter = 1
            }
[...]
```

Script was extracted from https://evotec.xyz/hub/scripts/pswindocumentation-powershell-module/ and after running it changing the parameters, the error occurs.

**Comment by PrzemyslawKlys** [comment]
Check `Get-Module -ListAvailable PSWriteWord`. Which version you have? 

You can do two things:
1. Import-Module PSWriteWord first (assuming you have the newest version
2. Simply Replace [ListItemType]:: with nothing. But you will also have this problem for heading type, alignment and so on. It's better to use the first version. 

Are you using modules PSGallery? 

Alternatively, you can take code from Examples on GitHub. I believe I've there are examples without `[ListItemTYpe]`

**Comment by carlosdoliveira** [comment]
> Check `Get-Module -ListAvailable PSWriteWord`. Which version you have?
> 
> You can do two things:
> 
> 1. Import-Module PSWriteWord first (assuming you have the newest version
> 2. Simply Replace [ListItemType]:: with nothing. But you will also have this problem for heading type, alignment and so on. It's better to use the first version.
> 
> Are you using modules PSGallery?
> 
> Alternatively, you can take code from Examples on GitHub. I believe I've there are examples without `[ListItemTYpe]`

Hey @PrzemyslawKlys, thanks for the quick answer. It's available at version 1.0.1. I removed ```[ListItemType]``` and let it empty but then I got the following error: 
``` PowerShell
VERBOSE: Get-TypesRequired - FinalList:
VERBOSE: Connect-WinExchange - Using Non-MFA option
VERBOSE: Request-Credentials - Reading password from file C:\Temp\Important\Password-O365-Klabin.txt
Get-WinO365Exchange : The term 'Get-WinO365Exchange' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation\0.5.0\PSWinDocumentation.ps1:107 char:55
+ ...     'ExchangeOnline' { $DataInformation = Get-WinO365Exchange -TypesR ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WinO365Exchange:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING: There was no data to process Office 365 documentation. Check configuration.
VERBOSE: Time to gather data: 00:00:07.0281980
VERBOSE: Time to create documents: 00:00:00.0011825
VERBOSE: Time total: 00:00:07.0573898
``` 

It sounds like the function Get-WinO365Exchange was not loaded from the module even though I've installed PSWinDocumentation directly from PSGallery through the cmdlet ```Install-Module PSWinDocumentation```

Below you can find all installed cmdlets I have: 
![image](https://user-images.githubusercontent.com/23587299/62652506-eea77a00-b931-11e9-8175-d29f6c2a02f0.png)

**Comment by PrzemyslawKlys** [comment]
Ye, I've been reworking modules that PSWinDocumentation needs to work. Mainly PSWinDocumentation.AD/PSWinDocumentation.O365 and few others. I'll test this tomorrow and see if I've not broken things while doing changes.

**Comment by PrzemyslawKlys** [comment]
Ok,

```
Install-Module PSwindocumentation -Force -AllowClobber
```

Also, I've updated an example on the Examples and main website. Keep in mind that PSWinDocumentation is work in progress. While the AD part is pretty and all the O365 part is far from optimal. That should make it "work". 

The docs are also not updated but:

- [x] https://github.com/EvotecIT/PSWinDocumentation.O365
- [x] https://github.com/EvotecIT/PSWinDocumentation.AD 

Those are the places where the "dev" where I update how the resources look like. Notice thou that PSWinDocumentation connects automatically to MSOL and ExchangeOnline but it doesn't do that for Teams, Skype and so on. If you want to utilize the main PSWinDocumentation package with all the types provided by PSWindocumentation.O365 you need to connect things yourself. I've also added examples with Dashimo/Documentimo directly using PSWinDocumentation.O365. May be worth going that road. 

Main PSWinDocumentation project won't be updated to support everything that is available as separate modules until I'm ready with O365 / AD types.

**Comment by PrzemyslawKlys** [comment]
Can you try:

```
Update-Module PSWriteWord
```

I've changed few things and dropped using `using namespace`. Should solve your issue

**Comment by PrzemyslawKlys** [comment]
Updated documentation on website by removing types.
