### ISSUE TITLE
Unable to find type [Container]

### ISSUE THREAD

**Issue by Kirtar22** [EvotecIT/PSWinDocumentation#21]

**Comment by PrzemyslawKlys** [comment]
Did you use Install-Module method?

**Comment by Kirtar22** [comment]
Hey, 

I was able to solve the issue. I think , the issue was related to multiple versions of the same modules were loaded. Once I cleaned that up, it worked like a cham !! Thanks

**Comment by PrzemyslawKlys** [comment]
Great!
