### ISSUE TITLE
Error: Unable to find type [DocX]

### ISSUE THREAD

**Issue by Grem66** [EvotecIT/PSWinDocumentation#22]
Happy to admit, first time trying your files, getting a puzzling error.

![image](https://user-images.githubusercontent.com/40968151/68847654-dff01080-0733-11ea-873f-378bcef52e5f.png)

Tried the standard built in template, tried the empty doc from your downloads and tried a fresh docx (blank and saved). Tried changing to dotx in case it was the wrong format. Tried on two Win10 laptops, 1903 with Office 2016 and 1909 with Office 365. Exact same behaviour (both PS 5.1), every time its unable to find type.

![image](https://user-images.githubusercontent.com/40968151/68848913-fdbe7500-0735-11ea-9838-3a4c141b2685.png)

![image](https://user-images.githubusercontent.com/40968151/68848980-1a5aad00-0736-11ea-83e3-31edf78e6f0a.png)

**Comment by PrzemyslawKlys** [comment]
add at the top of the script:
- `Import-Module PSWriteWord -Force`

if you don't have it `Install-Module PSWriteWord -Force`

**Comment by PrzemyslawKlys** [comment]
Just FYI - stuff may have changed for O365 - https://github.com/EvotecIT/PSWinDocumentation.O365 

You can also test this project. As I am not sure what is the state of PSwinDocumentation for O365.

**Comment by Grem66** [comment]
Added the line at the top script, and separately in PS have done Install and Update Module. PSWriteWord is 1.0.2. Same error. This is on O365 laptop, can try 2016 in 8-9 hrs

**Comment by PrzemyslawKlys** [comment]
did you close powershell session?

**Comment by PrzemyslawKlys** [comment]
Shouldn't matter because Word is not used. It's generated outside of word.

**Comment by PrzemyslawKlys** [comment]
Can you try:

```
Update-Module PSWriteWord
```

I've changed few things and dropped using `using namespace`. Should solve your issue

**Comment by PrzemyslawKlys** [comment]
Update-module pswindocumentation
