### ISSUE TITLE
Unable to find type [Container].

### ISSUE THREAD

**Issue by Grem66** [EvotecIT/PSWinDocumentation#23]
Hey, sorry, got busy with regular work. Your response time is seriously impressive!
Dived into this again.
First updated modules PSWinDocumentation (still 0.5.1), PSSharedGoods (now 0.0.107), PSWriteWord (now 1.1)
Then used script here to remove old versions: http://sharepointjack.com/2017/powershell-script-to-remove-duplicate-old-modules/
Updated ADEssentials.psd1 on line 54 to require 0.0.107

Script runs until it hits an error:
![image](https://user-images.githubusercontent.com/40968151/69017168-0d75dc00-0a0a-11ea-8d9a-4df8c1514563.png)

Guessing that line (haven't modified the script since first setting up) - param([Container] $WordDocument,- is referring to the doc variable, so the start of your script:
![image](https://user-images.githubusercontent.com/40968151/69017464-19629d80-0a0c-11ea-96ec-3c37908d0501.png)

And the folder in question
![image](https://user-images.githubusercontent.com/40968151/69017437-eddfb300-0a0b-11ea-9a6c-b747220435aa.png)

After the errors this in powershell
![image](https://user-images.githubusercontent.com/40968151/69017490-49aa3c00-0a0c-11ea-9021-9ae59bff6056.png)

And the ReportO365 docx opens, blank.

**Comment by PrzemyslawKlys** [comment]
Please update pswindocumentation and try again
