### ISSUE TITLE
Unable to find type [ListItemType] (Same as #20)

### ISSUE THREAD

**Issue by Grem66** [EvotecIT/PSWinDocumentation#24]
Don't think I can re-open cdaniel's issue, but in the meanwhile, trying the AD side, I get the same error.

Module versions I'm running
![image](https://user-images.githubusercontent.com/40968151/69022104-05746700-0a1f-11ea-918a-1033990ba213.png)

Tried including Update-Module PSWriteWord at the top of the ps1, that didn't change anything...

**Comment by PrzemyslawKlys** [comment]
Can you search for [ListItemType] and let me know where do you see it? I believe it's only in .ps1 config file that you run. You can simply remove [ListeItemType]:: and leave the text such as 'Bullet' alone.

Please do 

```
Update-module PSWindocumentation
```

it should update all needed modules. Restart PowerShell before/after installation.

The problem for those "unknown" types comes from:

```
using namespace Xceed.Words.NET
using namespace Xceed.Document.NET
```

PowerShell doesn't seem to like using shortnames in modulees. I've now removed those from PSWriteWord and so you need to use full names instead. However if one wants he can run those two commands at the top of the script and it should work. 

But please try without it first. I would like to fix this once and for all to not have this types missing problem as it's been a pain.

**Comment by Grem66** [comment]
Ran Update-Module, restart PS, still the same issues.
Removed [ListItemType]::, Numbered changed to 'Numbered' and ran
New error was [HeadingType]::, this also changed to apostrophes around remaining type (Heading1 usually) and ran
New error was [Alignment]::, this also changed to apostrophes around remaining type (Both usually) and ran
New error was [TableDesign]::, this also changed to apostrophes around remaining type (ColorfulGridAccent5 usually) and ran

Think that was the last of the issues, and success!
Cheers!

**Comment by PrzemyslawKlys** [comment]
Where did you got config file from? I updated it on website I believe some time ago? But maybe i skipped some stuff.

**Comment by Grem66** [comment]
Got it from here last week: https://evotec.xyz/pswindocumentation-audit-active-directory-passwords/

**Comment by PrzemyslawKlys** [comment]
I’ll update it. I thought i fixed all configs with strings instead of types. Thank you

**Comment by PrzemyslawKlys** [comment]
Thank you, updated blog. Sorry for the inconvenience.
