### ISSUE TITLE
different things

### ISSUE THREAD

**Issue by Heinzler** [EvotecIT/PSWinDocumentation#27]
Thanks for the nice presentation at psconf and the great work! I used the module for the first time today with "Run-Documentation.ActiveDirectory.ps1" and I like it. You said suggestions are welcome and I would have a few. :) 
If it's OK I would like to summarize them here or should I open multiple issues?

**Comment by PrzemyslawKlys** [comment]
It depends if those are related or not really. I do plan to refresh module, add new functionalities but I've been busy with other stuff.

**Comment by Heinzler** [comment]
I know, I updated Adessentials that week twice a day :) 

These things are not really urgent. I don't really have a lot of experience with github so I would name a few things and you tell me what to do.

**Comment by PrzemyslawKlys** [comment]
Open them as issues and as I will be refreshing PSWinDocumentation I will address it. It was a tough choice of putting the Show- functions from ADEssentials into PSWindocumentation or leave it in ADEssentials. But the goal is what you see in ADEssentials will find it's way into PSWindocumentation in the full dashboard. I still have to finish up all commands from GPOZaurr before I get back to PSWindocumentation and I may need to fix PSWriteHTML to be able to split content into different files.
