### ISSUE TITLE
More information about GPOs

### ISSUE THREAD

**Issue by alexsmid** [EvotecIT/PSWinDocumentation#3]
It would be nice to get more information about the GPOs, for example:
Links
Security Filtering
Maybe even Settings, but this might be to much.

**Comment by PrzemyslawKlys** [comment]
This basically requires reading .xml file

```
Get-GPOReport -All -ReportType Xml | Out-File C:\test.xml
```

Doable but requires some effort. Not really sure if XML is consistent as well. Unless someone already did it and I just need to make sure to process it properly.

**Comment by alexsmid** [comment]
I think something like this would work
```
#Get the information for Links
[xml]$GPOReport = $gpo | Get-GPOReport -ReportType XML  

#Get the security filtering
$GPOPermission = $gpo | Get-GPPermission -All | Where {$_.Permission -eq "GpoApply"} 

#CanonicalName of the OU the GPO is linked to
'Links'         = $GPOReport.GPO.LinksTo.SOMPath 

#If the link is enabled or disabled
'Enabled'       = $GPOReport.GPO.LinksTo.Enabled 

#Will display the user/group in the format "CONTOSO\SamAccountname"
'Security Filtering'= $GPOPermission.Trustee.Domain + "\" + $GPOPermission.Trustee.Name 
```

Only problem would be that as there can be multiple links, this would have to be a table inside the table

**Comment by PrzemyslawKlys** [comment]
Just FYI I have working code for this. I just have started rebuilding PSWinDocumentation to be flexible. Will take a moment but it will look like this. There will be also export to Excel so I guess some parts can go to Excel. Simplified version locally. 

![image](https://user-images.githubusercontent.com/15063294/43865816-fa063824-9b63-11e8-8a53-9d2de71753bf.png)

**Comment by PrzemyslawKlys** [comment]
New version (WIP):

![image](https://user-images.githubusercontent.com/15063294/43958678-86f9b44c-9cac-11e8-86a7-fa5c89d4f715.png)

With 10 columns:

![image](https://user-images.githubusercontent.com/15063294/43959622-b4f86c32-9caf-11e8-8f7f-1d01cc8aa664.png)

With all columns:

![image](https://user-images.githubusercontent.com/15063294/43959876-86cefc08-9cb0-11e8-8fa2-3d1286b71472.png)

**Comment by alexsmid** [comment]
Looks amazing!

**Comment by PrzemyslawKlys** [comment]
New version released. Has this built-in.
