### ISSUE TITLE
Trouble with Get-ADUser

### ISSUE THREAD

**Issue by JonasAgius** [EvotecIT/PSWinDocumentation#4]
Hey,
got trouble on a Server 2016 DC, getting this Error (changed Domain to X):

AUSFÜHRLICH: Start-ActiveDirectoryDocumentation - Getting Forest Information
AUSFÜHRLICH: Start-ActiveDirectoryDocumentation - Working...1
AUSFÜHRLICH: Start-ActiveDirectoryDocumentation - Working...2
AUSFÜHRLICH: Start-ActiveDirectoryDocumentation - Getting domain information
Get-ADUser : Unter "DC=X,DC=local" kann kein Objekt mit der ID "CN=ServerAdmin,CN=Managed Service Accounts,DC=X,DC=local" gefunden werden.
In C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation\0.0.5\Private\PSADDomain.ps1:19 Zeichen:187
+ ... DGroupMember -Server $Domain -Recursive | Get-ADUser -Server $Domain)
+                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CN=ServerAdmin,...,DC=X,DC=local:ADUser) [Get-ADUser], ADIdentityNotFoundException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsoft.ActiveDirectory.Management.Commands.GetADUser
 
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-21-1795207983-3442354869-3719958033-512 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-21-1795207983-3442354869-3719958033-518 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-21-1795207983-3442354869-3719958033-519 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-21-1795207983-3442354869-3719958033-520 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-544 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-548 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-549 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-550 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-551 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-552 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-556 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-557 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-573 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-578 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Get-PrivilegedGroupsMembers - Group S-1-5-32-580 in X.local (S-1-5-21-1795207983-3442354869-3719958033)
AUSFÜHRLICH: Start-ActiveDirectoryDocumentation - Creating section for X.local - Domain Controllers
AUSFÜHRLICH: Start-ActiveDirectoryDocumentation - Creating section for X.local - FSMO Roles

**Comment by PrzemyslawKlys** [comment]
Thanks for reporting this. I will most likely rebuild some code to stop using `pipeline` in favour of foreach. It's much easier to tell what is wrong and where.

**Comment by PrzemyslawKlys** [comment]
If you do `Get-ADUser -Server 'x.local'` does it work?

**Comment by JonasAgius** [comment]
Thanks for Troubleshooting. This seems the problem, I got this:

[cid:image001.png@01D42D9E.36C156B0]

Also tried the FQDN of the DC, with the same result.


Aufmerksame Grüße aus Offenbach

________________________________

[cid:IQS_b6267050-c416-4fec-bfa2-5070bf9d1c2a.jpg]

Jonas Agius
Teamleiter / IT Systemadministrator

Tel. 069 / 83 83 292 - 201
Tel. Support 069 / 83 83 292 - 0
Fax 069 / 857 000 01
jonas.agius@iq-solutions.de<mailto:jonas.agius@iq-solutions.de>
www.iq-solutions.de<http://www.iq-solutions.de>


________________________________
Sind Sie zufrieden? Lassen Sie es uns mit nur einem Klick wissen!

[cid:Smiley-Green_f61ba5ab-3db3-4e68-a16d-3998533895bb.jpg]<https://app.customerthermometer.com/?template=log_feedback&hash=dbd84df4&embed_data=dGVtcGVyYXR1cmVfaWQ9MiZ0aGVybW9tZXRlcl9pZD00NjE5Mw==&e=jonas.agius@iq-solutions.de&f=Jonas&l=Agius&c=&c1=reply@reply.github.com;PSWinDocumentation@noreply.github.com&c2=AW:%20[EvotecIT/PSWinDocumentation]%20Trouble%20with%20Get-ADUser%20(#4)&c3=&c4=&c5=&c6=&c7=&c8=&c9=&c10=>  [cid:Smiley-Amber_14c8e8fb-7d75-4526-8355-3ff333e4778e.jpg] <https://app.customerthermometer.com/?template=log_feedback&hash=67b76e09&embed_data=dGVtcGVyYXR1cmVfaWQ9MyZ0aGVybW9tZXRlcl9pZD00NjE5Mw==&e=jonas.agius@iq-solutions.de&f=Jonas&l=Agius&c=&c1=reply@reply.github.com;PSWinDocumentation@noreply.github.com&c2=AW:%20[EvotecIT/PSWinDocumentation]%20Trouble%20with%20Get-ADUser%20(#4)&c3=&c4=&c5=&c6=&c7=&c8=&c9=&c10=>   [cid:Smiley-Red_f3c83486-ac11-45a5-9b18-7e66194b3315.jpg] <https://app.customerthermometer.com/?template=log_feedback&hash=d025bf58&embed_data=dGVtcGVyYXR1cmVfaWQ9NCZ0aGVybW9tZXRlcl9pZD00NjE5Mw==&e=jonas.agius@iq-solutions.de&f=Jonas&l=Agius&c=&c1=reply@reply.github.com;PSWinDocumentation@noreply.github.com&c2=AW:%20[EvotecIT/PSWinDocumentation]%20Trouble%20with%20Get-ADUser%20(#4)&c3=&c4=&c5=&c6=&c7=&c8=&c9=&c10=>
________________________________

IQ Solutions GmbH

Christian-Pleß-Str. 11-13 | Haus 1
63069 Offenbach am Main

Geschäftsführung: Mario Lozic, Jörg Pfeiffer
Eintrag: Amtsgericht 63065 Offenbach am Main, HRB 11159
USt-Id.Nr.: DE 202745012

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This E-Mail contains information that is privileged, confidential and/or exempt from disclosure under applicable law. If you are not the intended recipient and/or if you have received this communication by error, please delete this mail and notify the sender immediately. Any use, distribution, transmission, printing, copying or dissemination of this E-Mail in any way or in any matter is strictly prohibited.

________________________________

Von: Przemysław Kłys <notifications@github.com>
Gesendet: Montag, 6. August 2018 13:53
An: EvotecIT/PSWinDocumentation <PSWinDocumentation@noreply.github.com>
Cc: Jonas Agius - IQ Solutions GmbH <jonas.agius@iq-solutions.de>; Author <author@noreply.github.com>
Betreff: Re: [EvotecIT/PSWinDocumentation] Trouble with Get-ADUser (#4)


If you do Get-ADUser -Server 'x.local' does it work?

**Comment by PrzemyslawKlys** [comment]
Please attach picture via GITHUB. It wasn't attached so I can't see this.

**Comment by PrzemyslawKlys** [comment]
Please provide update on this?

**Comment by JonasAgius** [comment]
![error](https://user-images.githubusercontent.com/42141533/44036225-91f8d582-9f11-11e8-9f17-3dd0efdaaf3f.png)

Sorry was busy (in a Project). I got this while doing Get-ADUser at the DC

**Comment by PrzemyslawKlys** [comment]
`Get-Aduser -Server 'iq.local' -Filter *`

Anyways, new version will have diff approach for priviliged groups so shouldn't break on this.

**Comment by JonasAgius** [comment]
perfect thx

**Comment by PrzemyslawKlys** [comment]
New version was released. Feel free to test this one.

**Comment by PrzemyslawKlys** [comment]
Closing as i assume problem is solved.
