### ISSUE TITLE
script run trouble - listtype

### ISSUE THREAD

**Issue by cajunitalian** [EvotecIT/PSWinDocumentation#5]
Running into this issue when using your preferred method:

![image](https://user-images.githubusercontent.com/1809840/44590824-138af780-a78a-11e8-9504-04677c1ef4f4.png)

Using the bulk script found here: https://evotec.xyz/pswindocumentation-version-0-1-with-word-excel-export/

**Comment by PrzemyslawKlys** [comment]
Make sure you have imports on top. And that all modules are installed. And powershell 5.

**Comment by PrzemyslawKlys** [comment]
Closing as no response - I assume problem is solved.

**Comment by NightyLive** [comment]
I have same issue,

Win10 Pro x64
PS ver. 5.1
Running PS ISE in both user and admin mode.

Installed modules with this :
```
Install-Module -Name PSWinDocumentation -Force
Install-Module -Name PSWinDocumentation.AD -Force
Install-Module -Name PSWinDocumentation.O365 -Force
Install-Module -Name PSWriteWord
Install-Module -Name PSWriteExcel 
Install-Module -Name PSSharedGoods
```

And uncomented "Import-Module" lines in your scripts.

The line that cause the error : 
`                    TocListItemType = [ListItemType]::Numbered`

**Comment by PrzemyslawKlys** [comment]
Remove [LisItemType]:: and just leave Numbered as a string. Should work. New examples on GitHub show this.
