### ISSUE TITLE
ParameterBindingArgumentTransformationException when running PSWriteExcel

### ISSUE THREAD

**Issue by AgentWong** [EvotecIT/PSWinDocumentation#6]
At the part of the script when it begins to write to an Excel portion I get this error:
Save-WordDocument : Cannot process argument transformation on parameter 'WordDocument'. Cannot convert the

"System.Object[]" value of type "System.Object[]" to type "Xceed.Words.NET.Container".

At C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation\0.1.0\Public\PSAD.ps1:49 char:53

+ $FilePath = Save-WordDocument -WordDocument $WordDocument `

+ ~~~~~~~~~~~~~

+ CategoryInfo : InvalidData: (:) [Save-WordDocument], ParameterBindingArgumentTransformationException

+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Save-WordDocument

Issue is with PSWriteExcel version 0.0.10

The problem goes away when I run PSWinDocumentation script without Export to Excel enabled and also if I uninstall the PSWriteExcel module and reinstall version 0.0.3

**Comment by PrzemyslawKlys** [comment]
You may want to give it a try with new version.

**Comment by AgentWong** [comment]
Sorry for the late reply!  New version works like a charm!  Thanks!

**Comment by PrzemyslawKlys** [comment]
Thats great!
