### ISSUE TITLE
Unable to find type [Xceed.Words.NET.Container]

### ISSUE THREAD

**Issue by AlexYoung28** [EvotecIT/PSWinDocumentation#7]
Hi, 

Firstly, great script think it's awesome! I've just tried the latest one and i'm getting the following error

Unable to find type [Xceed.Words.NET.Container] is this an easy fix?

**Comment by PrzemyslawKlys** [comment]
Do you have PSWriteWord installed?
```
Install-Module PSWriteWord 
```
and then in the script you are about to start 
```
Import-Module PSWriteWord 
```

**Comment by PrzemyslawKlys** [comment]
Also please provide
```
$PSVersionTable
```

**Comment by AlexYoung28** [comment]
Just tried that and same issue

Unable to find type [Xceed.Words.NET.Container].
At C:\Users\alex.NSM-SIDCUP.001\Documents\WindowsPowerShell\Modules\PSWriteWord\Public\PSWordMain.ps1:26 char:110
+ ... eFromPipeline, Mandatory = $true)][Xceed.Words.NET.Container]$WordDoc ...
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Xceed.Words.NET.Container:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Save-ExcelDocument : Cannot bind argument to parameter 'ExcelDocument' because it is null.
At C:\Users\alex.NSM-SIDCUP.001\Documents\WindowsPowerShell\Modules\PSWinDocumentation\Public\Start-DocumentationAD.ps1:63 char:56
+ ... $ExcelData = Save-ExcelDocument -ExcelDocument $ExcelDocument -FilePa ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Save-ExcelDocument], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Save-ExcelDocument
 
VERBOSE: Time to gather data: 00:00:14.3045330
VERBOSE: Time to create documents: 00:00:00.4924543
VERBOSE: Time total: 00:00:14.9474380

PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value                                                                                                                                                             
----                           -----                                                                                                                                                             
PSVersion                      5.1.17134.228                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                           
BuildVersion                   10.0.17134.228                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                               
SerializationVersion           1.1.0.1

**Comment by PrzemyslawKlys** [comment]
How are you actually starting this script? How your config file looks like?

**Comment by AlexYoung28** [comment]
Ah i feel silly now! i found the issue and it was the person behind the keyboard :) it's all fixed and working now :) thank you once again for a fantastic script :)

**Comment by PrzemyslawKlys** [comment]
That's great! But can you tell me what it was? Maybe I can add some additional checks to make sure when people run it it doesn't break or give meaningful warning.
